### PR TITLE
[Currency Bot] Bumped tedious from 15.1.3 to 18.1.0

### PR DESCRIPTION
**Pull request by kirrg001**
Tada!

### CODE REVIEW

**Comment by kirrg001** [comment]
@aryamohanan Do we have a card for that to increase the support at Otel?

**Comment by aryamohanan** [comment]
> @aryamohanan Do we have a card for that to increase the support at Otel?

Created one INSTA-1561, OpenTelemetry instrumentation for tedious only covers tedious version 15, so we can close this PR for now and consider update later.

**Comment by kirrg001** [comment]
> Created one INSTA-1561, OpenTelemetry instrumentation for tedious only covers tedious version 15, so we can close this PR for now and consider update later.

Thanks. I added the label "Currency" to 1561.
Could you close this PR and update the `currencies.json` to avoid further PR's for Tedious for now? You can push that straight to main. There is a flag `ignoreUpdates`.

**Comment by aryamohanan** [comment]
Added the package to the ignore list for currency. Closing the PR for now.

**Pull request closed without merging**
