### PR TITLE
[Currency Bot] Bumped sqs-consumer from 9.1.0 to 10.1.0

### PR DESCRIPTION
**Pull request by kirrg001**
Tada!

### CODE REVIEW

**Comment by aryamohanan** [comment]
They've updated their codebase to transition to ESM, highlighting it as a possible breaking change. However, they continue to support existing CommonJS configurations. You can find more details at https://github.com/bbc/sqs-consumer/compare/v9.1.0...v10.0.0.
[PR](https://github.com/bbc/sqs-consumer/pull/476)

**Comment by kirrg001** [comment]
https://github.com/bbc/sqs-consumer/releases/tag/v10.0.0

**Comment by kirrg001** [comment]
Seems fine for me as they build cjs & esm.

**Comment by kirrg001** [comment]
> Built files are outputted into ./dist/esm, ./dist/cjs and ./dist/types

This is their new deployment dist structure. We are using.

> requireHook.onModuleLoad('sqs-consumer', instrument);

This is still working fine.

**Pull request merged**
