### PR TITLE
chore(package.json): added the missing carets in package.json

### PR DESCRIPTION
**Pull request by athirasomanath**
This PR is really regarding the dev dependencies. To maintain consistency across devdependencies, I have added caret for all missing packages. 

refs: [120539](https://instana.kanbanize.com/ctrl_board/56/cards/120539/details/)

(Suggesting and open for further discussion regarding the dependencies. Although it needs digging into the package history to make a decision to keep the dependency versions with or without caret. )

### CODE REVIEW

**Comment by kirrg001** [comment]
FYI there is an existing issue which you can refer to: 120539

**Review by basti1302 — APPROVED** [review]
LGTM, thanks!

**Review by kirrg001 — APPROVED** [review]
👍 

We can mark the consistency subtask as done, but leave the ticket open regarding this idea. Move back to backlog.

> using a caret ^ for development dependencies does not give any transparency for us which latest minor version we are testing against, because only the lock file get's updated and not the package.json

**Comment by athirasomanath** [comment]
Reverted the caret for "@elastic/elasticsearch-v7.9.0" as it is failing for node v10

**Review by aryamohanan — APPROVED** [review]

**Pull request merged**
