### PR TITLE
[Currency Bot] Bumped patch/minor dependencies

### PR DESCRIPTION
**Pull request by instanacd**
Tada!

### CODE REVIEW

**Comment by kirrg001** [comment]
pg did not publish any release notes. Waiting.

**Comment by aryamohanan** [comment]
Suggestion: If our tests are successful, we can move forward with the updates and create a card to track the progress on the issue https://github.com/brianc/node-postgres/issues/3315, ensuring it does not block other updates.

**Comment by kirrg001** [comment]
I didn't expect that 5 days later we still have no release notes :(

> Suggestion: If our tests are successful, we can move forward with the updates and create a card to track the progress on the issue https://github.com/brianc/node-postgres/issues/3315, ensuring it does not block other updates.

Yes lets do that. https://jsw.ibm.com/browse/INSTA-15082

**Comment by kirrg001** [comment]
Same problem with pg-native. No release notes.
https://github.com/brianc/node-postgres/tree/master/packages/pg-native

**Review by kirrg001 — APPROVED** [review]

**Pull request merged**
