### PR TITLE
[Currency Bot] Bumped superagent from 9.0.2 to 10.0.0

### PR DESCRIPTION
**Pull request by instanacd**
Tada!

[INSTA-12427](https://jsw.ibm.com/browse/INSTA-12427)

- [x] check which breaking changes
- [x] Check if node v14 still working
- [x] Wait for the JIRA ticket and link it to it 
- [x] merge it with a proper commit msg as single commit with ticket reference

### CODE REVIEW

**Comment by abhilash-sivan** [comment]
They have added support for `brotli compression format` and did some dependency updates alongside code refactoring. The existing functionalities haven't changed. changes are available [here](https://github.com/ladjs/superagent/compare/v9.0.2...v10.0.0)

**Comment by kirrg001** [comment]
> They have added support for brotli compression format and did some dependency updates alongside code refactoring. The existing functionalities haven't changed. changes are available [here](https://github.com/ladjs/superagent/compare/v9.0.2...v10.0.0)

Yeah, the v10 major release doesn't make any sense to me and its nowhere explained.
There is IMO no need to run multiple major versions of superagent 👍

**Comment by kirrg001** [comment]
We probably need to revalidate [this comment.](https://github.com/ladjs/superagent/pull/1812#issuecomment-2268875910)

**Comment by kirrg001** [comment]
Commit msg:

> feat: added support for superagent v10

**Comment by abhilash-sivan** [comment]
> We probably need to revalidate [this comment.](https://github.com/ladjs/superagent/pull/1812#issuecomment-2268875910)

seems like the test completed successfully

**Comment by yigaldviri** [comment]
Hi there, sorry to interrupt but I think that superagent 10.0 isn't compatible with Node 14 (and I see you have a check here that it does).
Im the author of [this pr](https://github.com/ladjs/superagent/pull/1812) that triggered the whole version changing and we noticed after publishing that one of the dependencies of an added dependency requires Node 16. There's [a PR](https://github.com/ladjs/superagent/pull/1813) on that that waited to be merged

**Review by kirrg001 — APPROVED** [review]

**Review by abhilash-sivan — APPROVED** [review]

**Pull request merged**
