### PR TITLE
chore: fixed the linting issue for tsoa files

### PR DESCRIPTION
**Pull request by aryamohanan**
Linting appears to be broken on main

### CODE REVIEW

**Review by kirrg001 — CHANGES_REQUESTED** [review]
The tsoa folder is in the estlintignore:

> test/tracing/frameworks/tsoa/build

There must be a different reason that there is a problem suddenly?

**Comment by aryamohanan** [comment]
> test/tracing/frameworks/tsoa/build

 I am experiencing issue with Prettier.

**Comment by kirrg001** [comment]
And which issue?

**Comment by aryamohanan** [comment]
> And which issue?

We discussed this offline and added the tsoa build files in prettier ignore file as these files are generated from ts files.

**Review by kirrg001 — APPROVED** [review]

**Pull request merged**
