### PR TITLE
[Currency Bot] Bumped patch/minor dependencies

### PR DESCRIPTION
**Pull request by instanacd**
Created a card to test the new Prisma feature TypedSQL, [INSTA-13639](https://jsw.ibm.com/browse/INSTA-13639)

### CODE REVIEW

**Comment by aryamohanan** [comment]
Prisma introduced a preview feature **TypedSQL** https://github.com/prisma/prisma/releases/tag/5.19.0.

https://www.prisma.io/blog/announcing-typedsql-make-your-raw-sql-queries-type-safe-with-prisma-orm?utm_source=twitter&utm_campaign=typedsql

**Comment by kirrg001** [comment]
> Prisma introduced a preview feature TypedSQL

Has that an effect on us or on our Prisma support? What do we need to do?

**Comment by aryamohanan** [comment]
> Has that an effect on us or on our Prisma support? What do we need to do?

I think we need to test this and add testcase, may be in a separate card.

**Review by aryamohanan — APPROVED** [review]
LGTM

**Pull request merged**
